import os
from dotenv import load_dotenv

load_dotenv()



SQLALCHEMY_DATABASE_URI= os.environ.get("SQL_ALCHEMY_DATABASE_URI")
SECRET_KEY= os.environ.get("SECRET_KEY")

class Config:
    SQLALCHEMY_DATABASE_URI = SQLALCHEMY_DATABASE_URI
    SECRET_KEY = SECRET_KEY
    SQLALCHEMY_TRACK_MODIFICATIONS = True
    print("SQLALCHEMY_DATABASE_URI",SQLALCHEMY_DATABASE_URI)

